function out1 = ig_set_structure_fields_gui(in1)
%IG_SET_STRUCTURE_FIELDS_GUI		- set structure fields gui

bgcol = [0.752941176470588 0.752941176470588 0.752941176470588];

h = findobj('Tag','set structure fields gui');
if ~isempty(h); delete(h); end;
   
h0 = figure('Backingstore','off','Name','set structure fields gui',...
	    'Resize','On', 'Menubar','none','Number','off',...
	    'Color',bgcol, ...
	    'InvertHardcopy','off', ...
	    'NumberTitle','off', ...
	    'PaperPosition',[18 180 576 432], ...
	    'PaperUnits','points', ...
	    'Position',[536 144 376 420], ...
	    'Tag','set structure fields gui', ...
	    'ToolBar','none');




if nargin > 0

	fn = fieldnames(in1);

	hfn = uicontrol('Parent',h0, ...
			   'Units','points', ...
			   'BackgroundColor',[1 1 1], ...
			   'ListboxTop',0, ...
			   'Units','normalized', ...
			   'Position',[0.1 0.85 0.5 0.05], ...
			   'String',fn, ...
			   'Style','popupmenu', ...
			   'Tag','fn', ...
			   'Value',1);

	hval = uicontrol('Parent',h0, ...
			   'Units','points', ...
			   'BackgroundColor',[1 1 1], ...
			   'ListboxTop',0, ...
			   'Units','normalized', ...
			   'Position',[0.7 0.85 0.2 0.05], ...
			   'String','', ...
			   'Style','edit', ...
			   'Tag','value');


	UD.hfn		= hfn;
	UD.hval		= hval;

	UD.s		= in1;


	fnames = get(hfn,'String');
	fname = fnames{1};
	set(hval,'String',num2str(getfield(UD.s,fname)));

	set(hfn,'CallBack',['UD=get(gcf,''UserData''); i = get(UD.hfn,''Value''); fnames = get(UD.hfn,''String'');',...
	    'fname = fnames{i}; set(UD.hval,''String'',num2str(getfield(UD.s,fname)))']);

	set(hval,'CallBack',['UD=get(gcf,''UserData''); val = str2num(get(UD.hval,''String''));',...
	    'i = get(UD.hfn,''Value''); fnames = get(UD.hfn,''String''); fname = fnames{i}; UD.s = setfield(UD.s,fname,val); set(gcf,''UserData'',UD);']);
end

hload = uicontrol('Parent',h0, ...
		   'Units','points', ...
		   'BackgroundColor',[0.5020    0.5020    1.0000], ...
		   'ListboxTop',0, ...
		   'Units','normalized', ...
		   'Position',[0.1 0.3 0.3 0.1], ...
		   'String','Load...', ...
		   'Tag','Load...');

hsave = uicontrol('Parent',h0, ...
		   'Units','points', ...
		   'BackgroundColor',[0.5020    0.5020    1.0000], ...
		   'ListboxTop',0, ...
		   'Units','normalized', ...
		   'Position',[0.6 0.3 0.3 0.1], ...
		   'String','Save...', ...
		   'Tag','Save...');

hclose = uicontrol('Parent',h0, ...
		   'Units','points', ...
		   'BackgroundColor',[0.5020    0.2510    0.2510], ...
		   'ListboxTop',0, ...
		   'Units','normalized', ...
		   'Position',[0.1 0.1 0.8 0.1], ...
		   'String','Continue...', ...
		   'Tag','Close');


UD.load		= hload;
UD.save		= hsave;
UD.hclose	= hclose;


set(gcf,'UserData',UD);



set(hload,'CallBack',['[filename,pathname]=uigetfile(''*.mat'',''Load options file...''); s = load([pathname filename]); UD.s = s.options; set(gcf,''UserData'',UD);',...
	    'ig_set_structure_fields_gui(UD.s);']);

set(hsave,'CallBack',['[filename,pathname]=uiputfile(''*.mat'',''Save options file...''); UD=get(gcf,''UserData''); options = UD.s; save([pathname filename],''options'');']);

set(hclose,'CallBack',['UD = get(gcf,''UserData''); out1 = UD.s; uiresume;']);

uiwait;

if nargout > 0,
    UD = get(gcf,'UserData');
    out1 = UD.s;

    delete(gcf);

end
	    



